name: laser_minecock
version: '${project.version}'
main: org.examplecock.laser_minecock.Laser_minecock
api-version: '1.20'

commands:
  spawnlaser:
    description: жоско наворачивает говна
    usage: /spawnlaser <x1> <y1> <z1> <x2> <y2> <z2>